export const adminSeeds = [
  {
    key: "tech" as const,
    email: "andre.pratama@gojek.com",
    name: "Andre Pratama",
    phone: "+6281234567890",
    gender: "Male",
    dob: "1985-05-15",
    education: "Master of Computer Science — Universitas Indonesia",
    address: "Pasaraya Blok M, Jl. Iskandarsyah II No.7, Jakarta Selatan",
    city: "Jakarta",
    province: "DKI Jakarta",
    summary:
      "VP of Engineering at Gojek with 12+ years of experience leading large-scale distributed systems and engineering teams. Oversees talent acquisition pipelines across multiple product verticals including GoRide, GoFood, and GoPay.",
    linkedin: "https://linkedin.com/in/andre-pratama",
  },
  {
    key: "creative" as const,
    email: "maya.siregar@traveloka.com",
    name: "Maya Siregar",
    phone: "+628129998877",
    gender: "Female",
    dob: "1988-09-21",
    education: "Bachelor of Visual Communication Design — ITB",
    address: "Jl. Pluit Selatan Raya, Penjaringan, Jakarta Utara",
    city: "Jakarta",
    province: "DKI Jakarta",
    summary:
      "Head of Design at Traveloka, leading the product design and brand experience teams. Responsible for building world-class design culture, employer branding, and recruiting top creative talent across Southeast Asia.",
    linkedin: "https://linkedin.com/in/maya-siregar",
  },
  {
    key: "fintech" as const,
    email: "surya.wijaya@dana.id",
    name: "Surya Wijaya",
    phone: "+628177665544",
    gender: "Male",
    dob: "1987-02-10",
    education: "MBA Finance — Universitas Gadjah Mada",
    address: "Jl. Wolter Monginsidi No.3, Kebayoran Baru, Jakarta Selatan",
    city: "Jakarta",
    province: "DKI Jakarta",
    summary:
      "Director of Operations at Dana Indonesia, overseeing product strategy, compliance, and talent acquisition for Indonesia's leading digital wallet platform. Manages strategic partnerships with OJK-regulated financial institutions.",
    linkedin: "https://linkedin.com/in/surya-wijaya",
  },
] as const;

export const seekerSeeds = [
  {
    key: "alice" as const,
    name: "Alice Hartono",
    email: "alice.hartono@gmail.com",
    phone: "+628111111111",
    gender: "Female",
    dob: "1997-07-12",
    city: "Bandung",
    province: "Jawa Barat",
    education: "Bachelor of Information Systems — Universitas Padjadjaran",
    address: "Jl. Merdeka No. 7, Bandung",
    summary:
      "Frontend engineer with 4 years of experience building production-grade React and Next.js applications. Skilled in TypeScript, state management with Zustand, and component library development. Looking for a senior-level role at a product-driven company.",
    linkedin: "https://linkedin.com/in/alice-hartono",
    portfolio: "https://alicehartono.dev",
  },
  {
    key: "bob" as const,
    name: "Bob Pratama",
    email: "bob.pratama@gmail.com",
    phone: "+628222222222",
    gender: "Male",
    dob: "1995-03-03",
    city: "Surabaya",
    province: "Jawa Timur",
    education: "Bachelor of Statistics — Institut Teknologi Sepuluh Nopember",
    address: "Jl. Ketintang No. 5, Surabaya",
    summary:
      "Data scientist with expertise in Python, SQL, and machine learning. Experienced in building predictive models, data pipelines, and business intelligence dashboards. Seeking opportunities to apply analytics in fintech or e-commerce.",
    linkedin: "https://linkedin.com/in/bob-pratama",
  },
  {
    key: "charlie" as const,
    name: "Charlie Wijaya",
    email: "charlie.wijaya@gmail.com",
    phone: "+628333333333",
    gender: "Male",
    dob: "1994-11-20",
    city: "Yogyakarta",
    province: "DI Yogyakarta",
    education: "Bachelor of Business Management — Universitas Gadjah Mada",
    address: "Jl. Malioboro No. 10, Sleman",
    summary:
      "Product operations lead with 5 years of experience in agile environments. Transitioning into product management with a focus on fintech and digital payments. Strong analytical background and stakeholder management skills.",
    linkedin: "https://linkedin.com/in/charlie-wijaya",
  },
  {
    key: "diana" as const,
    name: "Diana Sari",
    email: "diana.sari@gmail.com",
    phone: "+628444444444",
    gender: "Female",
    dob: "1996-06-18",
    city: "Jakarta",
    province: "DKI Jakarta",
    education: "Bachelor of Marketing — Universitas Bina Nusantara",
    address: "Jl. Pramuka No. 9, Jakarta Timur",
    summary:
      "Digital marketing strategist with 3 years of experience in B2B SaaS and agency environments. Proficient in Google Ads, Meta Ads, SEO, and content marketing. Passionate about data-driven campaign optimization.",
    linkedin: "https://linkedin.com/in/diana-sari",
  },
  {
    key: "eko" as const,
    name: "Eko Santoso",
    email: "eko.santoso@gmail.com",
    phone: "+628555555555",
    gender: "Male",
    dob: "1993-09-30",
    city: "Medan",
    province: "Sumatera Utara",
    education: "Bachelor of Computer Science — Universitas Sumatera Utara",
    address: "Jl. Iskandar Muda No. 15, Medan",
    summary:
      "Backend engineer with 5 years of experience building scalable APIs and microservices using Node.js, Go, and PostgreSQL. Passionate about fintech infrastructure, payment systems, and distributed computing.",
    linkedin: "https://linkedin.com/in/eko-santoso",
  },
  {
    key: "gina" as const,
    name: "Gina Putri",
    email: "gina.putri@gmail.com",
    phone: "+628577744411",
    gender: "Female",
    dob: "1998-01-25",
    city: "Jakarta",
    province: "DKI Jakarta",
    education: "Bachelor of Product Design — Universitas Pelita Harapan",
    address: "Jl. Kemang Raya No. 22, Jakarta Selatan",
    summary:
      "UX/UI designer with a strong portfolio in fintech and e-commerce product design. Experienced in user research, wireframing, prototyping with Figma, and design system creation. Looking for product design roles in innovative companies.",
    linkedin: "https://linkedin.com/in/gina-putri",
    portfolio: "https://dribbble.com/ginaputri",
  },
  {
    key: "testProfessional" as const,
    name: "Hadi Susanto",
    email: "hadi.susanto@gmail.com",
    phone: "+628999111111",
    gender: "Male",
    dob: "1990-01-01",
    city: "Jakarta",
    province: "DKI Jakarta",
    education: "Bachelor of Software Engineering — Universitas Indonesia",
    address: "Jl. Kebayoran Baru No. 12, Jakarta Selatan",
    summary:
      "Full-stack developer with 7 years of experience. Currently exploring senior engineering and tech lead opportunities. Active Professional subscription member with access to priority CV review and unlimited assessments.",
    linkedin: "https://linkedin.com/in/hadi-susanto",
  },
  {
    key: "testStandard" as const,
    name: "Indah Lestari",
    email: "indah.lestari@gmail.com",
    phone: "+628999222222",
    gender: "Female",
    dob: "1996-02-02",
    city: "Bandung",
    province: "Jawa Barat",
    education: "Bachelor of Information Technology — Telkom University",
    address: "Jl. Telekomunikasi No. 8, Bandung",
    summary:
      "Junior QA engineer and aspiring DevOps specialist. Currently on the Standard subscription plan, exploring automated testing and CI/CD pipeline roles in growing tech companies.",
    linkedin: "https://linkedin.com/in/indah-lestari",
  },
] as const;
